name: Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout        
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      
      -        
        name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0
      -
        name: Install Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go
      - 
        name: Build Centos Binary
        run: |
          cp .env.sample .env          
          CENTOS=1 mage build:binariesdocker
      # - 
      #   name: Test Go
      #   run: |
      #     mage test:go || true
      # -
      #   name: Test cgodocker
      #   run: |
      #     mage test:cgodocker || true
      # -
      #   name: Test gosec
      #   run: |
      #     mage test:gosec || true
      # -
      #   name: Test hardening
      #   run: |
      #     mage test:hardening || true
      -
        name: Package
        run: |
          go install github.com/google/go-licenses@latest
          CENTOS=1 mage build:rpmdocker
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpm.el7
          path: dist/app/rpm/*.rpm
          

