name: Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout        
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      
      -        
        name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0
      -
        name: Install Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go
      - 
        name: Build Binary
        run: |
          cp .env.sample .env          
          CENTOS=1 mage build:binaries
      - 
        name: Result
        run: |
          ls -la bin/
          ls -la build/foss
          

